### ISSUE TITLE
perfomance issue in CBOR parsing

### ISSUE THREAD

**Issue by lakshT** [FasterXML/jackson-dataformats-binary#111]
Hi,

I am using the following code to convert from CBOR data to a HashMap. 

CBORFactory cfac = new CBORFactory();
ObjectMapper mapper = new ObjectMapper(cfac);
HashMap<String, Object> map = mapper.readValue(inData, new TypeReference<HashMap<String, Object>>(){ });

This code is running multiple times for different data. The first time this code runs, the performance overhead is around 100ms. For all consecutive conversions, it reduces to about 4 ms. Can you help me identify the cause? Is there anything which I'm not doing properly?

Thanks,
Laksh

**Comment by cowtowncoder** [comment]
@lakshT In future, please use mailing lists for usage questions.

Your results sound quite typical for JVM startup / first call overhead -- there isn't much one can do typically, although if this is for web service, you could perhaps perform couple of reads and writes when starting up the service, to "warm up" JVM wrt code used.

One minor thing you can do to reduce per-call overhead is to create `ObjectReader`:

    ObjectReader reader = mapper.readerFor(new TypeReference<HashMap<String, Object>>(){ });

and use:

    Map<String, Object> map = reader.readValue(inData);

this will remove some of initialization cost; although in most cases difference is not huge.
