### ISSUE TITLE
Remove "final" modifier from `CBORParser`

### ISSUE THREAD

**Issue by jinzha** [FasterXML/jackson-dataformats-binary#129]
Hi CBOR developers,

I would use the CBOR lib in our project, but want to extend it to add some additional functionality. It looks like CBORParser defines a bunch of protected members which implies it could be extended, but it is "final" class, so can not be extended. 

Is it intended to not be extended? If not, can you please fix this by removing the final modifier?
BTW, the CBORGenerator is not final class.

**Comment by cowtowncoder** [comment]
No, `CBORParser` is not meant to be extended, although there is no strict need to have it be `final`. I can remove that easily.

Out of curiosity, do you have specific use for sub-classing?

**Comment by cowtowncoder** [comment]
I remove `final` modifier from `CBORParser` -- I can not recall explicit reason to add it, and no other parser or generator implementation is left final (at an earlier point some were).
This is for `2.9` branch and `master`, so will be included in `2.9.5` release once that is made (and eventually 3.0).

**Comment by jinzha** [comment]
Hi  cowtowncoder,

Thanks for quickly fixing it!

In our case, we would add a method to make CBORParser read from the specified offset of InputStream, the underling InputStream in our project support to read from a specified offset. I tried add below method to support this. Does it make sense to you?

public class CBORParserEx extends CBORParser {
      public void setOffset(int offset) {
            final ByteInputStream in = getInputStream();
            in.setOffset(offset);
            _currInputProcessed = offset;
           _inputPtr = _inputEnd = 0;
    } 
}

**Comment by jinzha** [comment]
HiTatu,

Thanks for quickly fixing it! May I know when will the 2.9.5 be released?

In our case, we would add a method to make CBORParser read from the 
specified offset of InputStream, the underling InputStream in our 
project support to read from a specified offset. I tried add below 
method to support this. Does it make sense to you?

public class CBORParserEx extends CBORParser {
     public void setOffset(int offset) {
         final ByteInputStream in = getInputStream();
         in.setOffset(offset);
         _currInputProcessed = offset;
         _inputPtr = _inputEnd = 0;
      }
}

Regards,
Jin

**Comment by cowtowncoder** [comment]
On modification: I would personally modify it by custom `InputStream` instead, and not try to do that on parser. Or, if you prefer, sub-classing `CBORFactory` and handling it here.
The only thing that would not achieve would be `_currInputProcessed`, and if that is important, the only way would be sub-classing.

As to `2.9.5`, likely some time in March, maybe in 2 weeks or so. Usually there's at least 2 months between patch releases at this point.

**Comment by jinzha** [comment]
Hi Tatu,

Thanks for your quick response!

In our case, there is a custom InputStream which supports to set read 
offset at any position, but it seems that the CBORParser has its own 
internal InputBuffer that caches a batch of data read from InputStream, 
so adjusting the offset of InputStream will not immediately impact on 
CBORParser, it will read from its InputBuffer until no more data and 
need to load more from InputStream.

Is it possible to avoid using InputBuffer in CBORParser?

Regards,
Jin

**Comment by cowtowncoder** [comment]
Use of input buffer is pretty essential for reasonable performance -- overhead of single byte reads would be significant. So design does not allow skipping of buffering.
It is possible to "flush" content buffered but not (yet) read at end of decoding (using method `releaseBuffered()` on parser).

But I guess I am not sure which aspect of buffering would be problematic for you: location, or something else?

**Comment by jinzha** [comment]
Hi Tatu,

On 3/5/18 12:16 PM, Tatu Saloranta wrote:
>
> Use of input buffer is pretty essential for reasonable performance -- 
> overhead of single byte reads would be significant. So design does not 
> allow skipping of buffering.
> It is possible to "flush" content buffered but not (yet) read at end 
> of decoding (using method |releaseBuffered()|on parser).
>
> But I guess I am not sure which aspect of buffering would be 
> problematic for you: location, or something else?
>
Yes. it is location. In our case, the capability to read value in a 
customized order is required. So we just go through the InputStream to 
collects the offsets for each value, then read values in a customized 
order by setting the offset of InputStream.

Based on my performance testing, using Jackson CBOR for above case is 
12% slower than using serialization module implemented by ourselves.

I feel like the way we use Jackson CBOR to read value on specified 
offset is not suitable for the current Jackson CBOR implementation that 
uses a internal buffer to cache data. In our case, the process is like 
set offset1 -> parse value1 -> set offset2 -> parse value2 -> ....
When setting offset, actually it resets the InputBufer(see below 
setOffset() mehtod). During parse value, it will load 8K data to 
InputBuffer, but parse 1st value only, then reset again, load another 8K 
data and parse 2nd value, this process might not be that efficient I 
think. What do you think?

public class CBORParserEx extends CBORParser {
     public void setOffset(int offset) {
         final ByteInputStream in = getInputStream();
         in.setOffset(offset);
         _currInputProcessed = offset;
         _inputPtr = _inputEnd = 0;
      }
}

Regards,
Jin

**Comment by jinzha** [comment]
Hi Tatu,

Thanks for your response as always!

On 3/5/18 12:16 PM, Tatu Saloranta wrote:
>
> Use of input buffer is pretty essential for reasonable performance -- 
> overhead of single byte reads would be significant. So design does not 
> allow skipping of buffering.
> It is possible to "flush" content buffered but not (yet) read at end 
> of decoding (using method |releaseBuffered()|on parser).
>
> But I guess I am not sure which aspect of buffering would be 
> problematic for you: location, or something else?
>
Yes. it is location. In our case, the capability to read value in a 
customized order is required. So we just go through the InputStream to 
collects the offsets for each value, then read values in a customized 
order by setting the offset of InputStream.

Based on my performance testing, using Jackson CBOR for above case is 
12% slower than using serialization module implemented by ourselves.

I feel like the way we use Jackson CBOR to read value on specified 
offset is not suitable for the current Jackson CBOR implementation that 
uses a internal buffer to cache data. In our case, the process is like 
set offset1 -> parse value1 -> set offset2 -> parse value2 -> ....
When setting offset, actually it resets the InputBufer(see below 
setOffset() mehtod). During parse value, it will load 8K data to 
InputBuffer, but parse 1st value only, then reset again, load another 8K 
data and parse 2nd value, this process might not be that efficient I 
think. What do you think?

public class CBORParserEx extends CBORParser {
     public void setOffset(int offset) {
         final ByteInputStream in = getInputStream();
         in.setOffset(offset);
         _currInputProcessed = offset;
         _inputPtr = _inputEnd = 0;
      }
}

Regards,
Jin

**Comment by cowtowncoder** [comment]
In general intent is not to modify underlying `InputStream`, but to construct separate `CBORParser` instances for distinct input documents. This is safer and overhead for parser instances should be modest.

But your use case where random-access is required is quite different from kinds of use cases I have considered. I can see how parser, as is, would have significant overhead.

If you do know the length of document (or document fragment) to parse you can prevent `InputStream` from exposing more content than is needed: so, for example, if document is known to be 400 bytes long, only return up 400 bytes. That would avoid significant overhead of reading 8000 bytes, discarding 7600.

**Comment by jinzha** [comment]
Hi Tatu,

Thanks for the analysis!

In our cases, the length of documents might be variable I think, it 
looks like our random-access case is not good case using the existing 
Jackson CBOR.

Regards,
Jin

**Comment by cowtowncoder** [comment]
@jinzha Yes, it sounds like this is the case unfortunately. Optimizing for such access is tricky -- although something like this is actually implemented in Jackson JSON parser for `DataInput`. It results in -40% performance decrease (which may be more than what would happen with `InputStream`; perhaps `DataInput` access pattern is more difficult for JVM to optimize), but does work with no look-ahead/read-ahead (since `DataInput` does not have means to detect end of input; reader must know how much is still needed).
Similarly, async parsers (for JSON, Smile; perhaps in future for CBOR) use different access pattern as input is fed, not read via blocking stream.

So it would be possible to implement no-caching parser; and make that pluggable via `CBORFactory`. I don't have time to do that myself, but if anyone wants to try that in future, I can help with integration.

For now your best bet may be to something else that exists, esp. if you have your own decoder.

**Comment by jinzha** [comment]
Hi Tatu,

Thanks you very much!

It is very nice experience to use Jackson CBOR library. I think you are 
right, we probably have to keep to use own decoder for now.

Regards
Jin
