### ISSUE TITLE
Inconsistent support for FLUSH_PASSED_TO_STREAM

### ISSUE THREAD

**Issue by cakofony** [FasterXML/jackson-dataformats-binary#155]
Cbor and Smile serializers attempt to flush streams on close when AUTO_CLOSE_TARGET is disabled, even if FLUSH_PASSED_TO_STREAM is also disabled.

**Comment by cowtowncoder** [comment]
Thank you for reporting this, showing the place where checks were missing. I had to do bit of massaging and ended up manually merging, to get this in 2.10 -- implementation has changed quite a bit between 2.x and (upcoming) 3.0.
