### ISSUE TITLE
[smile] Ignore USE_BIG_DECIMAL_FOR_FLOATS for NaN/Infinity

### ISSUE THREAD

**Issue by manuel-hegner** [FasterXML/jackson-dataformats-binary#158]
The problem described in fasterxml/jackson-databind#1028 still seems to be a problem if the smile format is used.

**Comment by cowtowncoder** [comment]
@manuel-hegner Would it be possible to come up with a simple unit test & include version numbers relevant? That'd make it easier to verify and fix?

**Comment by cowtowncoder** [comment]
I can not actually reproduce this, using test from issue linked, so would need help show how it occurs.

**Comment by cowtowncoder** [comment]
Can not proceed without reproduction, closing but may be reopened with a test case against latest minor version.
