### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/ASL2.0'

### ISSUE THREAD

**Issue by Grabber** [FasterXML/jackson-dataformats-binary#184]
```
More than one file was found with OS independent path 'META-INF/ASL2.0'
```

```
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> More than one file was found with OS independent path 'META-INF/ASL2.0'
```

**build.prop**
```
android {
    packagingOptions {
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
    }
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.10.0'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.10.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.10.0'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-avro:2.10.0'
}
```

**Comment by cowtowncoder** [comment]
I am not quite sure what the problem reported is. Yes, all Jackson components contain License information, which is the way to indicate license compatibility. Path is fixed, for obvious reasons.
This is the way things are.

**Comment by Grabber** [comment]
@cowtowncoder, the issue is that packagingOptions has to be set at App level and in my case I'm generating a library, if I just set packagingOptions at library level it doesn't work.

**Comment by cowtowncoder** [comment]
I don't think there is much Jackson can do about this, although I am open to suggestions.
Will close for now as "nothing we can do".

**Comment by Alexandr-Ilyin** [comment]
also can not build project after adding jackson as dependency

**Comment by cowtowncoder** [comment]
@Alexandr-Ilyin It is probably a problem with your build tools: they should not barf on such metadata. So if possible, make sure you are using latest versions of tooling available.
