### ISSUE TITLE
I have a fix for IonAnnotationTypeDeserializer on version 2.10.x but this fix is no longer necessary on master. Should I still push it?

### ISSUE THREAD

**Issue by ankel** [FasterXML/jackson-dataformats-binary#191]
Hello,

I have a bug resulted from the interaction between IonObjectMapper and a plain old Json string (without class name annotated).

I have here a test and a fix for it (base on the 2.10 branch). However, on master, my fix is no longer necessary.

What is the timeline for 3.0 releases? Do you think it's still worthwhile to create a PR for this fix on for version 2.10? What are the steps for me to open a PR to that branch?

Best,

**Comment by cowtowncoder** [comment]
Yes, I think fix against 2.10 branch makes sense. 3.0 (master) is not close to being released. Currently we are working on 2.11, and there will probably be further 2.x releases being developed concurrent to 3.0.

**Comment by ankel** [comment]
I've created #192 which contains the fix and test cases for the issue here. Resolve issue.
