### ISSUE TITLE
Unable To Resolve CBOR Dependency Via SBT

### ISSUE THREAD

**Issue by PeterLambCSA** [FasterXML/jackson-dataformats-binary#193]
> [error] SERVER ERROR: Not Implemented url=http://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.9.10/jackson-dataformat-cbor-2.9.10.pom

Due to Maven Central change from HTTP to HTTPS.

> Effective January 15, 2020, The Central Repository no longer supports insecure communication over plain HTTP and requires that all requests to the repository are encrypted over HTTPS.
> 
> If you're receiving this error, then you need to replace all URL references to Maven Central with their canonical HTTPS counterparts:
> 
> Replace http://repo1.maven.org/maven2/ with https://repo1.maven.org/maven2/
> 
> Replace http://repo.maven.apache.org/maven2/ with https://repo.maven.apache.org/maven2/
> 
> If for any reason your environment cannot support HTTPS, you have the option of using our dedicated insecure endpoint at http://insecure.repo1.maven.org/maven2/
> 
> For further context around the move to HTTPS, please see https://blog.sonatype.com/central-repository-moving-to-https.

**Comment by PeterLambCSA** [comment]
The issue was actually in SBT. Apologies. Closing this issue.

**Comment by cowtowncoder** [comment]
Yes, Sonatype just announced they stopped accepting non-https requests.
