### ISSUE TITLE
Any plan to support thrift - 0.11.0 and above

### ISSUE THREAD

**Issue by ericxsun** [FasterXML/jackson-dataformats-binary#209]
it seems that the [jackson-dataformat-thrift](https://github.com/FasterXML/jackson-dataformat-thrift) does not support any more. 

So I'm wondering is theree any plan to support thrift-format in this repo? 

Thanks a lot.

**Comment by cowtowncoder** [comment]
Yeah I never had time to implement that format module so it never really existed even though I created repo and added skeleton to start from.

I do not have current plans to work on it; technically it should be quite doable.

**Comment by ericxsun** [comment]
okay, thanks any way
