### ISSUE TITLE
"Can not create generator" in _nonByteSource()

### ISSUE THREAD

**Issue by sloopjon** [FasterXML/jackson-dataformats-binary#21]
I'm studying the binary backends in preparation for possibly writing one of my own.  Each of them has a _nonByteSource() method in the factory class that throws an UnsupportedOperationException with the message, "Can not create generator for non-byte-based source".  Do I understand correctly that it should say "parser", rather than "generator"?

**Comment by cowtowncoder** [comment]
@sloopjon yes, that sounds like a copy-paste error. I'll see if I can see where, and fix those.

**Comment by cowtowncoder** [comment]
Fixed, thanks again, good catch.
