### ISSUE TITLE
Avro null deserialization

### ISSUE THREAD

**Issue by marcospassos** [FasterXML/jackson-dataformats-binary#216]
We found another issue related to schema evaluation, after deserialization of a null value. After a few hours of debugging, we found that the root issue [has already been fixed](https://github.com/FasterXML/jackson-dataformats-binary/commit/2978de217bc076b9d7615c91173aa963aafdc0b2#diff-f1d5995cc2009c62f822a9e5da3ebd00), but it was not included in the latest release.

Is there any particular reason not to release this fix for 2.11.x versions?

**Comment by cowtowncoder** [comment]
Looking at #146 PR (for #145) originally submitted against master; I would not be against fix for 2.x if anyone has time to back port the change.

Since there is a new feature, it would have to go in 2.12(.0) however.

**Comment by marcospassos** [comment]
Is it ok if I provide a PR including only the fix for the null serialization issue?

**Comment by marcospassos** [comment]
PR opened.

**Comment by cowtowncoder** [comment]
Yes that makes sense.

**Comment by marcospassos** [comment]
Any ETA for 2.11.2?

**Comment by cowtowncoder** [comment]
I was hoping to hold off for bit longer as 2.11.1 was only released 1 month ago and total number of fixes is still quite low. But there are couple of important fixes so I think I will release this within a week, maybe over the weekend.

**Comment by marcospassos** [comment]
Thank you @cowtowncoder :)

**Comment by cowtowncoder** [comment]
2.11.2 was released on August 2nd, 2020.

**Comment by marcospassos** [comment]
Thank you @cowtowncoder.
