### ISSUE TITLE
(cbor) Overflow in `BigDecimal` input (by ossfuzzer)

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformats-binary#267]
(note: discovered by https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32579)

Looks like there is an unhandled Overflow for certain types of `BigDecimal` values fuzzer creates.
Would be nice to cleanly handle; but at very least catch exception and rethrow, if need be.
Does not immediately appear to be a security related as JDK code reports it based on checks.

**Comment by cowtowncoder** [comment]
Hmmmh. Looks like comparing `scale` to any static limit will not solve the issue since number of trailing zeroes can vary.
Catching exception seems ugly but might be the only way...

**Comment by fmeum** [comment]
I think catching and not stripping zeros in that case could be sufficiently backwards compatible. It would have the advantage that this would never throw for any representable BigDecimal, which people may rightfully expect given that a default of stripping zeros is a bit arbitrary.

**Comment by cowtowncoder** [comment]
New fix done in `jackson-databind` to just catch the exception: since this is continuation of 
#264 will close as dup.
