### ISSUE TITLE
Add `SmileGenerator.Feature.LENIENT_UTF_ENCODING` for lenient handling of broken Unicode surrogate pairs on writing

### ISSUE THREAD

**Issue by kireet** [FasterXML/jackson-dataformats-binary#276]
When encoding some invalid user generated data, we encounter `JsonGenerationException`s with the message `Unmatched first part of surrogate pair`. This didn't occur when using text serialization. 

It seems there's a CBOR option to avoid this exception, `CBORGenerator.Feature.LENIENT_UTF_ENCODING`, but not one for Smile. It would be great to add this feature. 

To reproduce, just try to serialize an invalid string, such as `"\uD83D"`.

**Comment by cowtowncoder** [comment]
Sounds like a good idea, hoping to implement when I have time!
