### ISSUE TITLE
Doc links lead to 404 Not found

### ISSUE THREAD

**Issue by axelczk** [FasterXML/jackson-dataformats-binary#279]
Hello,

I'm working on a new project using your library to deserialize CBOR and was looking for your doc but the link inside the wiki returns a 404 not found. 

Could you please provide a new link to access to your doc ? 

Thanks

**Comment by axelczk** [comment]
Nvm I read the full message and found the javadoc. But you should update your wiki to use the new github domain.

**Comment by cowtowncoder** [comment]
Yes, I've noticed that deprecated killing links in a few projects. Too bad there's on way that I know of to do PRs for wikis.
Fixed links for this repo.
