### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by zidingz** [FasterXML/jackson-dataformats-binary#299]
Hey there!

I belong to an open source security research community, and a member (@occia) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by occia** [comment]
As supplementary, I put the found security bugs inside the huntr platform for responsible disclosure. You can login as this github repo's developer to see the detail reports:
- [report 1](https://www.huntr.dev/bounties/d75fa6d9-e70f-4caf-823a-a9f444081f68/)
- [report 2](https://www.huntr.dev/bounties/fa555c8b-f3c4-45e4-8171-9ef602d0b0cc/)

**Comment by cowtowncoder** [comment]
@zidingz Some of Jackson repos have it, so I'd recommend look at:

https://github.com/FasterXML/jackson-databind/

but basically there are 2 routes:

1. Report issues via Tidelift (do not have to be a customer, they will handle disclosures with dev team) OR
2. Send email to `info` at fasterxml dot com -- this will also go (eventually) to dev team.
