### ISSUE TITLE
Interest in EXI for JSON processor

### ISSUE THREAD

**Issue by danielpeintner** [FasterXML/jackson-dataformats-binary#33]
Hi,

based on https://github.com/EXIficient/exificient-for-json I use Jackson to convert JSON from/to EXI4JSON (see https://www.w3.org/TR/exi-for-json/).

EXI4JSON is  a compact format for JSON based on EXI technology.

I was wondering whether you are interested in such a PR?

Thanks,

-- Daniel

**Comment by cowtowncoder** [comment]
@danielpeintner anything that can be exposed as a token stream -- that is, fits within processing model Jackson uses -- should be fair game. It might make sense to start as a separate repo, and if and when things work well, add as a sub-project here?

So, sure, more the merrier!

**Comment by danielpeintner** [comment]
Thanks for the clarification @cowtowncoder!

I will work in a  separate repo first and keep you informed.

**Comment by danielpeintner** [comment]
In the meanwhile I implemented EXI4JSON with Jackson support (see https://github.com/EXIficient/exificient-for-json/tree/master/src/main/java/com/siemens/ct/exi/json/jackson).

I did run my own tests but I wonder whether you have a certain set of testcases one should run also.

**Comment by danielpeintner** [comment]
I wonder whether it is possible to extend the list of binary dataformats (see https://github.com/FasterXML/jackson-dataformats-binary/#overview) with EXI4JSON.

**Comment by cowtowncoder** [comment]
@danielpeintner Sure, thanks for reminding me!

**Comment by cowtowncoder** [comment]
Added links both from this repo's README and main `jackson` portal.

**Comment by danielpeintner** [comment]
Thanks!
