### ISSUE TITLE
Support `StreamReadConstraints.maxDocumentLength` validation for CBOR, Smile

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-dataformats-binary#392]
https://github.com/FasterXML/jackson-core/blob/2.16/src/main/java/com/fasterxml/jackson/core/StreamReadConstraints.java

equivalent of https://github.com/FasterXML/jackson-dataformats-text/issues/430 and #358

In particular, the 2 new ones (in 2.16)
* maxDocumentLength
* maxNameLength

These settings are not likely to be supported for data formats in this project. Some support already exists for the pre-existing StreamReadConstraints settings.

This issue specifically for supporting `maxDocumentLength` validation; #475 is for name length validation.

**Comment by cowtowncoder** [comment]
Limited to CBOR, Smile for this issue. (as two implementations are quite similar and probably be worked on at same time).
May/should create separate ones for Avro, Protobuf, Ion; those implementations quite different so not that much shared work.
