### ISSUE TITLE
How to use the same ?

### ISSUE THREAD

**Issue by neeraj332** [FasterXML/jackson-dataformats-binary#40]
Hi Friends,
I was trying to use this library for one of my project, but I don't know how to use the same.
I want to send a Java object form client (written in Java) to server (written in C) and prints the values of object on my server. I tried to use serialisation, but it was also not working. Some one suggested me to use CBOR and I was googling, but not able to find any proper implementation of the same.

I got this library and trying to use this, but I am not able to find any main method or way to use the same.

My final aim is to send the Java object from java client to C server, and print the values of object on my server.

Is it possible with using this library.
If anybody implemented the same kind of stuff, request you kindly provide the suggestion.

Thanks in advance.

**Comment by cowtowncoder** [comment]
@neeraj332 This is an issue tracker for filing issues, and not a user support forum. But we do have user discussion group at:

https://groups.google.com/forum/#!forum/jackson-user

which is for questions like these.

As to your question: CBOR module is an extension to main Jackson databind:

https://github.com/FasterXML/jackson-dataformats

and you will use it the same as JSON functionality, except constructing `ObjectMapper` which CBOR encoder:

    ObjectMapper mapper = new ObjectMapper(new CBORFactory());

beyond that all standard usage works: for example:

    byte[] serialized = mapper.writeValueAsBytes(objectToSend);
