### ISSUE TITLE
Avro Schema generation: allow mapping Java Enum properties to Avro String values

### ISSUE THREAD

**Issue by jlous** [FasterXML/jackson-dataformats-binary#494]
With json, I could always extend an enum (on both sender and receiver ends), consider it a backwards compatible change,  and the receiver could parse both old and new documents equally well.

With avro, altering an enum makes the entire schema incompatible, and an updated schema can not be used to read old docs.
For all my use cases, serialising all enums as string would be a completely acceptable strategy for avoiding this problem, and much preferable to versioned formats,
but jacksons avro support does not currently seem to offer this.  

So I'm hoping for a new feature switch for avro: WRITE_ENUMS_AS_STRINGS or similar.
 
In my case I only really care about serialising, since the receiver is on a completely different platform, but I guess parity on the deserialising side would be natural to include.

**Comment by cowtowncoder** [comment]
Would this be possible wrt Avro schema limitations? Would new type be defined as Union, allowing both String and Enum? And which direction is the change? (older schema exception String, new Enum? Or vice versa)

At `JsonGenerator` (and so `AvroGenerator` subtype) level Enums are typically written using `writeString()` anyway (since JSON has no "Enum" type; conversion handled at databind level).
Same for `JsonParser`/`AvroParser`.

So I am not 100% sure I yet understand the ask here.

**Comment by jlous** [comment]
I sm suggesting an option where the generated schema for an enum would simply be String.

**Comment by cowtowncoder** [comment]
@jlous Ah ok. Depending on how implemented it might even be a general `MapperFeature`; I forget what the division is between model traversal (callbacks generated on serialization settings) and construction of Avro schema.

At this point I probably won't have time to work on this in near term but would be happy to help if anyone else wants to tackle it.

**Comment by MichalFoksa** [comment]
@jlous BTW: If you change in Avro schema enum to string type, serialization and deserialization should work already.

**Comment by MichalFoksa** [comment]
I try to avoid enum in Avro schema. Serializing enum into string is a good idea. 

@cowtowncoder 
How do you want to control this feature?

I think creating a new `AvroGenerator.Feature` would be best from API standpoint, but I do not know how to access `AvroGenerator.Feature` from VisitorFormatWrapperImpl.expectStringFormat(JavaType).

BTW: Here is a draft PR, where this feature is controlled by `enableWriteEnumAsString()` method:
```
AvroSchemaGenerator gen = new AvroSchemaGenerator()
    .enableWriteEnumAsString();
```

**Comment by cowtowncoder** [comment]
Ah. Sorry, saw this comment before adding a note on PR.

Yes, `AvroGenerator.Feature` would be better but I'd need to think of plumbing.

I think `AvroGenerator` might be available from `SerializerProvider` but not sure if that is properly initialized.

**Comment by MichalFoksa** [comment]
Let's continue discussion in PR https://github.com/FasterXML/jackson-dataformats-binary/pull/496.
