### ISSUE TITLE
Failed copy(): `IonValueMapper` does not override copy()

### ISSUE THREAD

**Issue by mr-robert** [FasterXML/jackson-dataformats-binary#497]
When calling .copy() on instance of IonValueMapper, I expect to get a new IonValueMapper with the same configuration. However, instead I get this expection.

I am using 2.12 but I checked the source of the latest version on github, and I do not see this method overridden.

I think that as this class is provided by Jackson themselves, they should provide the implementation of the overridden .copy() in IonValueMapper.

**Comment by mr-robert** [comment]
Thanks for this. I just ran into a similar issue, wondering if it should be fixed as well when using `IonValueMapper.builder(...)` methods, there is no overload in `IonValueMapper`, therefore the modules `IonValueModule` and `EnumAsIonSymbolModule` do not get attached if creating a mapper using `IonValueMapper.builder(...)` methods.

**Comment by cowtowncoder** [comment]
@mr-robert Could you file a separate issue for that?

**Comment by mr-robert** [comment]
Created #509
