### ISSUE TITLE
IonValueMapper.builder() not implemented, does not register modules

### ISSUE THREAD

**Issue by mr-robert** [FasterXML/jackson-dataformats-binary#509]
(follow-up from #497)

Using Jackson-dataformat-ion 2.17

When constructing a new `IonValueMapper` using constructor `new IonValueMapper(onSystem)` modules are registered:

Constructor code:
```
    public IonValueMapper(IonSystem ionSystem, PropertyNamingStrategy strategy) {
        super(new IonFactory((ObjectCodec)null, ionSystem));
        this.registerModule(new IonValueModule());
        this.registerModule(new EnumAsIonSymbolModule());
        this.setPropertyNamingStrategy(strategy);
    }
```

However, when constructing using builder:
`IonValueMapper.builder(ionSystem).build()`

the modules are not registered, ultimately by chain of method calls, the following code is run in IonObjectMapper.class : 
```
    public static Builder builder(IonFactory streamFactory) {
        return new Builder(new IonObjectMapper(streamFactory));
    }
```

this creates an IonObjectMapper , without registering IonValueModule or EnumAsIonSymbolModule.

I think that the correct/expected behavior should be that using IonValueMapper.builder(...) should ultimately create a mapper which is the same as using constructor with the same parameters. Therefore it seems that there may need to be some changes or additional builder overrides added in IonValueMapper.

Workaround for this is just to not use builder to create IonValueMapper , or manually registering the modules.

**Comment by cowtowncoder** [comment]
Ok this is bit tricky, due to static methods etc. But I will try to cobble something together.
For Jackson 3.0 `IonValueMapper` is deprecated, replaced by proper builder of `IonObjectMapper`, fwtw.

**Comment by cowtowncoder** [comment]
@mr-robert Did pr #510, merged; not confident it fully works but if you have a chance maybe you could have a look (`2.18.0-SNAPSHOT` should be built by CI, or build locally)?

**Comment by rnoack1** [comment]
Hi,

Wondering if you could explain this comment:

> For Jackson 3.0 IonValueMapper is deprecated, replaced by proper builder of IonObjectMapper, fwtw.

What is the "proper" builder in IonObjectMapper which corresponds to IonValueMapper, and does this builder exist in 2.18.x or only in upcoming 3.x Jackson?

**Comment by cowtowncoder** [comment]
It would be via builder-style construction, which does exist in 2.x branch too:

```
    IonMapper mapper = IonMapper.builder() // or 'builder(IonFactory f)`
                 // possible configuration and then
                .build();
```

in 3.0 `IonMapper` also has relevant `readValue(IonValue, targetType)` calls.
Actually, looking at 2.19 it too has these methods. But 2.19 has builders for `IonValueMapper` as well.

But overall, 3.0 will remove need for (and use of) `IonValueMapper`. I don't remember details of if and why it's still needed for 2.18 and later.
