### ISSUE TITLE
[protobuf] Some fields are left null

### ISSUE THREAD

**Issue by niksu7** [FasterXML/jackson-dataformats-binary#54]
Depending on field names and ordering, some fields are at times left out, probably when reading in proto message (since this can be reproduced also by writing the same content with c++ compiled proto interface and reading in with Jackson).

Attached JUnit test case with two ways to work around the problem (JsonPropertyOrder annotation or leaving out a nested object value).

Tested with version 2.8.7 (and same problems in previous versions too, but I haven't run  this exact test with any other version).
[TestProto.java.txt](https://github.com/FasterXML/jackson-dataformats-binary/files/821017/TestProto.java.txt)

**Comment by niksu7** [comment]
Correction: the problem must be in writing part, since the message is only 11 bytes when the nested object (testClass.b.d) is set, but 23 bytes when it is not set.

**Comment by niksu7** [comment]
I have a correction to this now, with minor changes to ProtobufGenerator.java and ByteAccumulator.java.

**Comment by cowtowncoder** [comment]
Thank you for the patch & test! I will backport this in 2.8.

**Comment by cowtowncoder** [comment]
As per notes on PR itself, it would appear that fix does not fix test failure (although naming of test class prevents it from getting run via Maven, hiding the fail).

**Comment by niksu7** [comment]
Oops, I'll check that today. I ran the test manually from Eclipse while testing the fix. It might be that I didn't test the latter manually as I assumed Maven would run the test...

**Comment by niksu7** [comment]
Yes, there was a stupid bug in the last commit.
Also renamed test + refactored it a bit.

**Comment by cowtowncoder** [comment]
Perfect, thank you! I merged it manually for 2.8 so will close PR but changes are the same.
Thank you once again for fixing this. Will be in 2.8.8 and 2.9.0.pr2

**Comment by cowtowncoder** [comment]
Hmmh. I suspect this is related to (or causing) #67, fwtw. Reordering of buffered content, perhaps harmless in some cases.

**Comment by niksu7** [comment]
I'll check. But if the test fails in 2.8.7, it can't be caused by this
change as it's not in 2.8.7.

On 5 Apr 2017 01:25, "Tatu Saloranta" <notifications@github.com> wrote:

Hmmh. I suspect this is related to (or causing) #67
<https://github.com/FasterXML/jackson-dataformats-binary/issues/67>, fwtw.
Reordering of buffered content, perhaps harmless in some cases.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FasterXML/jackson-dataformats-binary/issues/54#issuecomment-291652794>,
or mute the thread

**Comment by cowtowncoder** [comment]
@niksu7 Ah sorry, was meant just as FYI -- I was actually able to figure out what is/was happening with #67 and fix it.
