### ISSUE TITLE
[ion] Plans to include Amazon's Ion?

### ISSUE THREAD

**Issue by mahmoudimus** [FasterXML/jackson-dataformats-binary#7]
Not sure where to place this but I think Amazon's Ion is similar to cbor. 
- http://amznlabs.github.io/ion-docs/
- https://github.com/amznlabs/ion-java
- https://github.com/amznlabs/ion-java/issues/82

**Comment by cowtowncoder** [comment]
@mahmoudimus No plans to support Ion. As far as I recall, Ion is quite a bit more complicated than CBOR (I worked for Amazon, it was internally used for years).
But if someone writes a dataformat implementation, we could definitely host it or add links to project.

**Comment by mahmoudimus** [comment]
Makes sense. Thanks for the fast response 👍

**Comment by cowtowncoder** [comment]
@mahmoudimus forgot to mention that the issue tracker for new project ideas is actually https://github.com/FasterXML/jackson-future-ideas -- so if you want to have it open, feel free to file there.

**Comment by cowtowncoder** [comment]
@mahmoudimus Actually... funnily enough, there's a non-zero chance that I might collaborate with guys from Amazon who work on the format, and perhaps produce a backend. There is an old version of such a thing in existence.

**Comment by cowtowncoder** [comment]
I now have access to Ion backend implementation that I collaborated with Amazon developers. Unfortunately haven't had enough time for full clean up... but there is some progress.

**Comment by mahmoudimus** [comment]
👍  sounds awesome!

**Comment by mahmoudimus** [comment]
keep us updated, happy to help where I can.

**Comment by cowtowncoder** [comment]
This is finally in progress... stay tuned!

**Comment by trothwell** [comment]
Hasn't this been completed?

**Comment by cowtowncoder** [comment]
@trothwell Indeed, thanks!
