### ISSUE TITLE
[cbor] Android gradle

### ISSUE THREAD

**Issue by felipheggaliza** [FasterXML/jackson-dataformats-binary#90]
Is this library available on gradle?

I would like to use CBOR encoding/decoding on Android.

**Comment by cowtowncoder** [comment]
@felipheggaliza Library is released via Maven Central, so it should be available on all build systems that can use Maven artifact repositories. This includes gradle. So as far as I understand yes, you should be able to use this library on Android via Gradle build system.

**Comment by arpitsvm15** [comment]
Is the avro library available on gradle?Can I use it on android?

**Comment by cowtowncoder** [comment]
@arpitsvm15 All Jackson components are built as jars released via Maven Central, and I think Gradle typically uses this as source for dependencies. So as far as I know, yes, can use Avro module too from Gradle. I am not aware of any problems from using Android either, so AFAIK, yes, you can use it from Android.
